services:
  - type: web
    name: esp32-telegram
    env: python
    buildCommand: "pip install -r WebApp/requirements.txt"
    startCommand: "uvicorn WebApp.app.main:app --host 0.0.0.0 --port $PORT --workers 2"