
services:
  - type: web
    name: esp32-telegram-mqtt-bridge
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MQTT_BROKER
        value: broker.hivemq.com
      - key: MQTT_PORT
        value: 1883
      - key: DEVICE_ID
        value: device1
      - key: ALERT_DISTANCE_CM
        value: "50"
